#!/bin/sh

font=${1:-Sans}
width=${2:-1024}
lines=${3:-4}

cat <<EOF
double_buffer yes
use_xft yes
xftfont $font:pixelsize=34
xftalpha 0.15
draw_borders no
draw_graph_borders no
draw_shades yes
short_units yes

default_color 606060

alignment tl
maximum_width $(($width-16))
minimum_size $(($width-16))
gap_x 8
gap_y 6

mpd_host localhost

TEXT
EOF

sed "s,HOME,$HOME,g" <<'EOF'
${if_up wlan0}wlan0 ${wireless_essid wlan0} (${wireless_link_qual wlan0}%) ${endif}${if_up eth0}eth0${endif}${alignr}${alignr}${tail HOME/var/metar/kbos 1 300}
inbox ${if_mounted /net/mingus}${new_mails /net/mingus/srv/mail/decklin/.INBOX}${else}-${endif}${alignr}${mpd_status} ${mpd_vol}%
EOF

echo "\${font $font:pixelsize=36}"
for i in $(seq 1 $lines); do echo; done
echo -n "\${font $font:pixelsize=72}"
echo '${time %H:%M}${font} ${time %a %d %b}${alignr}${loadavg} ${battery}'
