var _dbk = default_base_keymap;
var _mbk = minibuffer_base_keymap;
var _dgk = default_global_keymap;
var _hbk = help_buffer_keymap;
var _cnk = content_buffer_normal_keymap;
var _ctk = content_buffer_text_keymap;

define_key(_dbk, "C-u", "cmd_deleteToBeginningOfLine");
define_key(_ctk, "C-u", "cmd_deleteToBeginningOfLine");
define_key(_mbk, "C-u", "minibuffer-cmd_deleteToBeginningOfLine");

define_key(_dbk, "escape", "universal-argument");
define_key(_mbk, "escape", "universal-argument");
define_key(_cnk, "escape", "universal-argument");

// define_key(_dgk, "S-q", "quit");
define_key(_dgk, "q", null);
define_key(_dgk, "M-k", "kill-current-buffer");
// define_key(_dgk, "_", "switch-to-buffer");
// define_key(_dgk, ":", "execute-extended-command");
// define_key(_dgk, "M-:", "eval-expression");
// define_key(_dgk, "m", null);
// define_key(_dgk, "C-p", "buffer-previous");
// define_key(_dgk, "C-n", "buffer-next");
// define_key(_dgk, "!", "shell-command");
// define_key(_dgk, "C-k", "kill-current-buffer");
// define_key(_dgk, "M-!", null);
// define_key(_dgk, "M-p", null);
// define_key(_dgk, "M-n", null);
// define_key(_dgk, "M-x", null);
// define_key(_dgk, "C-r", null);
// define_key(_dgk, "C-s", null);
// define_key(_dgk, "C-x C-c", null);
// define_key(_dgk, "C-x k", null);
// define_key(_dgk, "C-x b", null);

// define_key(_hbk, "q", null);
// define_key(_hbk, "C-p", "buffer-previous");
// define_key(_hbk, "C-n", "buffer-next");
// define_key(_hbk, "h", "cmd_scrollLeft", $category = "Scrolling");
// define_key(_hbk, "j", "cmd_scrollLineDown", $category = "Scrolling");
// define_key(_hbk, "k", "cmd_scrollLineUp", $category = "Scrolling");
// define_key(_hbk, "l", "cmd_scrollRight", $category = "Scrolling");
// define_key(_hbk, "C-e", "cmd_scrollLineDown", $category = "Scrolling");
// define_key(_hbk, "C-y", "cmd_scrollLineUp", $category = "Scrolling");
// define_key(_hbk, "g", "cmd_scrollTop", $category = "Scrolling");
// define_key(_hbk, "G", "cmd_scrollBottom", $category = "Scrolling");
// define_key(_hbk, "b", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_hbk, "C-u", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_hbk, "C-d", "cmd_scrollPageDown", $category = "Scrolling");
// define_key(_hbk, "C-b", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_hbk, "C-f", "cmd_scrollPageDown", $category = "Scrolling");
// define_key(_hbk, "$", "scroll-end-of-line", $category = "Scrolling");
// define_key(_hbk, "S-6", "scroll-beginning-of-line", $category = "Scrolling");
// define_key(_hbk, "0", "scroll-beginning-of-line", $category = "Scrolling");
// define_key(_hbk, "/", "isearch-forward");
// define_key(_hbk, "?", "isearch-backward");

// define_key(_cnk, "h", "cmd_scrollLeft", $category = "Scrolling");
// define_key(_cnk, "j", "cmd_scrollLineDown", $category = "Scrolling");
// define_key(_cnk, "k", "cmd_scrollLineUp", $category = "Scrolling");
// define_key(_cnk, "l", "cmd_scrollRight", $category = "Scrolling");
// define_key(_cnk, "C-e", "cmd_scrollLineDown", $category = "Scrolling");
// define_key(_cnk, "C-y", "cmd_scrollLineUp", $category = "Scrolling");
// define_key(_cnk, "g", "cmd_scrollTop", $category = "Scrolling");
// define_key(_cnk, "S-g", "cmd_scrollBottom", $category = "Scrolling");
// define_key(_cnk, "b", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_cnk, "C-u", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_cnk, "C-d", "cmd_scrollPageDown", $category = "Scrolling");
// define_key(_cnk, "C-b", "cmd_scrollPageUp", $category = "Scrolling");
// define_key(_cnk, "C-f", "cmd_scrollPageDown", $category = "Scrolling");
// define_key(_cnk, "$", "scroll-end-of-line", $category = "Scrolling");
// define_key(_cnk, "S-6", "scroll-beginning-of-line", $category = "Scrolling");
// define_key(_cnk, "0", "scroll-beginning-of-line", $category = "Scrolling");
// define_key(_cnk, "C-p", "buffer-previous");
// define_key(_cnk, "C-n", "buffer-next");
// define_key(_cnk, "/", "isearch-forward");
// define_key(_cnk, "?", "isearch-backward");
// define_key(_cnk, "n", "isearch-continue-forward");
// define_key(_cnk, ".", "isearch-continue-backward");
// define_key(_cnk, "o", "find-url");
// define_key(_cnk, "O", "find-url-new-buffer");
define_key(_cnk, "e", "find-alternate-url");
define_key(_cnk, "G", "find-url-new-buffer");
// define_key(_cnk, "p", "open-xsel-url");
// define_key(_cnk, "P", "open-xsel-url-new-buffer");
// define_key(_cnk, "F", "follow-new-buffer-background");
// define_key(_cnk, "y", "copy");
// define_key(_cnk, "c", null);
// define_key(_cnk, "a", "focus");
// define_key(_cnk, "close_bracket", "follow-next");
// define_key(_cnk, "open_bracket", "follow-previous");
// define_key(_cnk, "m", "bookmark");
// define_key(_cnk, "C-c", "stop-loading");
// define_key(_cnk, "C-t", "go-back");
// define_key(_cnk, "S-b", "go-back");
// define_key(_cnk, "C-]", "go-forward");
// define_key(_cnk, "\\", "view-source");
// define_key(_cnk, "C-v", "quote-next-input-mode");
// define_key(_cnk, "I", "quote-input-mode");
// define_key(_cnk, "M-v", null);
// define_key(_cnk, "C-q", null);
// define_key(_cnk, "C-x C-v", null);
// define_key(_cnk, "C-M-q", null);
// define_key(_cnk, "S-b", null);
// define_key(_cnk, "S-p", null);
// define_key(_cnk, "C-return", null);
// define_key(_cnk, ";", null);

define_key(_cnk, "C-x C-b", "switch-to-buffer");
define_key(_cnk, "@", "toggle-stylesheets");

define_key(_ctk, "escape", "unfocus");
define_key(_ctk, "C-2", "shell-twopass-url");
